# Generated by Django 4.0.4 on 2022-11-30 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolstudents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('date_Nasc', models.DateField()),
                ('sexo', models.CharField(max_length=1)),
                ('matricula', models.IntegerField()),
                ('curso', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('date_Nasc', models.DateField()),
                ('sexo', models.CharField(max_length=1)),
                ('ID_FUNCIONARIO', models.IntegerField()),
                ('date_entrada', models.IntegerField()),
                ('cargo', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.CreateModel(
            name='Diretoria',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('schoolstudents.funcionario',),
        ),
    ]
