# Generated by Django 4.0.5 on 2023-02-06 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolstudents', '0003_cargos_delete_diretoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='cargo',
        ),
    ]
