# Generated by Django 4.0.5 on 2023-02-06 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolstudents', '0004_remove_funcionario_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='cargo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='schoolstudents.cargos'),
        ),
    ]
