# Generated by Django 4.0.5 on 2023-02-06 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolstudents', '0002_aluno_funcionario_delete_student_diretoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargos',
            fields=[
                ('ID_CARGOS', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Diretoria',
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='ID_FUNCIONARIO',
            field=models.IntegerField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='schoolstudents.cargos'),
        ),
    ]
